// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Backend.Data;

#nullable disable

namespace Warehouse.Backend.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    partial class WarehouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Backend.Data.AlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AcknowledgementNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("acknowledgement_note");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_acknowledged");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("MachineId", "StartTime")
                        .HasDatabaseName("ix_alerts_machine_id_start_time");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.AppUserEntity", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("username");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_salt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Username")
                        .HasName("pk_app_users");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.ConsumptionAggregateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("average_kwh");

                    b.Property<decimal>("CostEuro")
                        .HasColumnType("numeric")
                        .HasColumnName("cost_euro");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_type");

                    b.Property<decimal>("TotalKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("total_kwh");

                    b.HasKey("Id")
                        .HasName("pk_consumption_aggregates");

                    b.HasIndex("ScopeType", "ScopeId", "PeriodStart")
                        .HasDatabaseName("ix_consumption_aggregates_scope_type_scope_id_period_start");

                    b.ToTable("consumption_aggregates", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.FloorplanLayoutEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BoundaryPointsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("boundary_points_json");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("integer")
                        .HasColumnName("canvas_height");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("integer")
                        .HasColumnName("canvas_width");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TextureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texture_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_floorplans");

                    b.ToTable("floorplans", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.FloorplanPinEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("device_type");

                    b.Property<int>("FloorplanLayoutId")
                        .HasColumnType("integer")
                        .HasColumnName("floorplan_layout_id");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_floorplan_pins");

                    b.HasIndex("FloorplanLayoutId")
                        .HasDatabaseName("ix_floorplan_pins_floorplan_layout_id");

                    b.ToTable("floorplan_pins", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.LightingDeviceEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsOn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_on");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_visible");

                    b.Property<DateTimeOffset>("LastChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_changed_at");

                    b.Property<string>("LastCommandSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_command_source");

                    b.Property<decimal>("LocationX")
                        .HasColumnType("numeric")
                        .HasColumnName("location_x");

                    b.Property<decimal>("LocationY")
                        .HasColumnType("numeric")
                        .HasColumnName("location_y");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("zone_id");

                    b.HasKey("DeviceId")
                        .HasName("pk_lighting_devices");

                    b.ToTable("lighting_devices", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.MachineEntity", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<decimal>("EnergyKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_kwh");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<decimal>("LocationX")
                        .HasColumnType("numeric")
                        .HasColumnName("location_x");

                    b.Property<decimal>("LocationY")
                        .HasColumnType("numeric")
                        .HasColumnName("location_y");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<int>("Rpm")
                        .HasColumnType("integer")
                        .HasColumnName("rpm");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_c");

                    b.Property<decimal>("VibrationMs2")
                        .HasColumnType("numeric")
                        .HasColumnName("vibration_ms2");

                    b.Property<string>("ZoneId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("zone_id");

                    b.HasKey("MachineId")
                        .HasName("pk_machines");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.MaintenanceRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertId")
                        .HasColumnType("text")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("closed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_records");

                    b.HasIndex("MachineId", "CreatedAt")
                        .HasDatabaseName("ix_maintenance_records_machine_id_created_at");

                    b.ToTable("maintenance_records", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("replaced_by_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying(120)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("Username", "TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_username_token_hash");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.RuleDefinitionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_seconds");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("TargetId")
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<decimal>("TemperatureThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_threshold");

                    b.Property<decimal>("VibrationThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("vibration_threshold");

                    b.HasKey("Id")
                        .HasName("pk_rules");

                    b.ToTable("rules", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.TelemetryEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("EnergyKwh")
                        .HasColumnType("numeric")
                        .HasColumnName("energy_kwh");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<int>("Rpm")
                        .HasColumnType("integer")
                        .HasColumnName("rpm");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal>("TemperatureC")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_c");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<decimal>("VibrationMs2")
                        .HasColumnType("numeric")
                        .HasColumnName("vibration_ms2");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_events");

                    b.HasIndex("MachineId", "Timestamp")
                        .HasDatabaseName("ix_telemetry_events_machine_id_timestamp");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.ZoneEntity", b =>
                {
                    b.Property<string>("ZoneId")
                        .HasColumnType("text")
                        .HasColumnName("zone_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("ZoneId")
                        .HasName("pk_zones");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Warehouse.Backend.Data.FloorplanPinEntity", b =>
                {
                    b.HasOne("Warehouse.Backend.Data.FloorplanLayoutEntity", "FloorplanLayout")
                        .WithMany("Pins")
                        .HasForeignKey("FloorplanLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_floorplan_pins_floorplans_floorplan_layout_id");

                    b.Navigation("FloorplanLayout");
                });

            modelBuilder.Entity("Warehouse.Backend.Data.RefreshTokenEntity", b =>
                {
                    b.HasOne("Warehouse.Backend.Data.AppUserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_app_users_username");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warehouse.Backend.Data.AppUserEntity", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Warehouse.Backend.Data.FloorplanLayoutEntity", b =>
                {
                    b.Navigation("Pins");
                });
#pragma warning restore 612, 618
        }
    }
}
